localhost:
  facebook:
    app_id: 135062956528724
    api_key: foo
    api_secret: "e8e44775af31ef5512b2bcbb37056128"
  linkedin:
    api_key: "JyWMuJzTBOd3KQOXSFQBTE2kkGByPD5A7v9BfarHyirmJxBOiNTCf5MPPg_N4l3v"
    api_secret: "Wl4SIwAxQVGBqPonx3h2ixrUHF7TQpqf7n2aEQrI-EeNKm-ZB70dxHrlHW7UZrRq"
recruitd.com:
  facebook:
    app_id: 129963327027314
    api_key: foo
    api_secret: "b496e5b2ee1a763ab13aa83e037b0f3f"
  linkedin:
    api_key: "7oTZAR9UMi-x0yDhX1zLCmXYKj6BaqGPvQJa506egi3QJ1puPhQXbmEYh_s4mihc"
    api_secret: "TRiY-biLXY9qgadg3PBCS3iZRWtya9eZogg_An-s2TryOtP7-H7-6LWFazftIEaM"